version: 2.1

orbs:
  node: circleci/node@4.5.1
  codecov: codecov/codecov@1.2.3

jobs:
  codecov-upload:
    docker:
      # replace with your preferred image
      - image: cimg/base:2021.04
    steps:
      - codecov/upload:
          file: /coverage

workflows:
    test:
      jobs:
        - node/test
        - codecov-upload:
          requires:
            - node/test
