version: 2.1

orbs:
  node: circleci/node@4.5.1
  codecov: codecov/codecov@1.2.3

jobs:
  codecov-upload:
    docker:
      # replace with your preferred image
      - image: cimg/node:16.4.1
    steps:
      - checkout
      - run: npm test
      - codecov/upload:
          file: /home/circleci/project/coverage

workflows:
    test:
      jobs:
        - node/test
        - codecov-upload:
            requires:
              - node/test
